// Copyright 2016 - 2025 The excelize Authors. All rights reserved. Use of
// this source code is governed by a BSD-style license that can be found in
// the LICENSE file.
//
// Package excelize providing a set of functions that allow you to write to and
// read from XLAM / XLSM / XLSX / XLTM / XLTX files. Supports reading and
// writing spreadsheet documents generated by Microsoft Excel™ 2007 and later.
// Supports complex components by high compatibility, and provided streaming
// API for generating or reading data from a worksheet with huge amounts of
// data. This library needs Go version 1.24.0 or later.

package excelize

import (
	"encoding/xml"
	"fmt"
	"strconv"
	"strings"
)

// ChartType is the type of supported chart types.
type ChartType byte

// This section defines the currently supported chart types enumeration.
const (
	Area ChartType = iota
	AreaStacked
	AreaPercentStacked
	Area3D
	Area3DStacked
	Area3DPercentStacked
	Bar
	BarStacked
	BarPercentStacked
	Bar3DClustered
	Bar3DStacked
	Bar3DPercentStacked
	Bar3DConeClustered
	Bar3DConeStacked
	Bar3DConePercentStacked
	Bar3DPyramidClustered
	Bar3DPyramidStacked
	Bar3DPyramidPercentStacked
	Bar3DCylinderClustered
	Bar3DCylinderStacked
	Bar3DCylinderPercentStacked
	Col
	ColStacked
	ColPercentStacked
	Col3D
	Col3DClustered
	Col3DStacked
	Col3DPercentStacked
	Col3DCone
	Col3DConeClustered
	Col3DConeStacked
	Col3DConePercentStacked
	Col3DPyramid
	Col3DPyramidClustered
	Col3DPyramidStacked
	Col3DPyramidPercentStacked
	Col3DCylinder
	Col3DCylinderClustered
	Col3DCylinderStacked
	Col3DCylinderPercentStacked
	Doughnut
	Line
	Line3D
	Pie
	Pie3D
	PieOfPie
	BarOfPie
	Radar
	Scatter
	Surface3D
	WireframeSurface3D
	Contour
	WireframeContour
	Bubble
	Bubble3D
	StockHighLowClose
	StockOpenHighLowClose
)

// ChartDashType is the type of supported chart dash types.
type ChartDashType byte

// This section defines the currently supported chart dash types enumeration.
const (
	ChartDashUnset ChartDashType = iota
	ChartDashSolid
	ChartDashDot
	ChartDashDash
	ChartDashLgDash
	ChartDashSashDot
	ChartDashLgDashDot
	ChartDashLgDashDotDot
	ChartDashSysDash
	ChartDashSysDot
	ChartDashSysDashDot
	ChartDashSysDashDotDot
)

// ChartLineType is the type of supported chart line types.
type ChartLineType byte

// This section defines the currently supported chart line types enumeration.
const (
	ChartLineUnset ChartLineType = iota
	ChartLineSolid
	ChartLineNone
	ChartLineAutomatic
)

// ChartTickLabelPositionType is the type of supported chart tick label position
// types.
type ChartTickLabelPositionType byte

// This section defines the supported chart tick label position types
// enumeration.
const (
	ChartTickLabelNextToAxis ChartTickLabelPositionType = iota
	ChartTickLabelHigh
	ChartTickLabelLow
	ChartTickLabelNone
)

// This section defines the default value of chart properties.
var (
	chartView3DRotX = map[ChartType]int{
		Area:                        0,
		AreaStacked:                 0,
		AreaPercentStacked:          0,
		Area3D:                      15,
		Area3DStacked:               15,
		Area3DPercentStacked:        15,
		Bar:                         0,
		BarStacked:                  0,
		BarPercentStacked:           0,
		Bar3DClustered:              15,
		Bar3DStacked:                15,
		Bar3DPercentStacked:         15,
		Bar3DConeClustered:          15,
		Bar3DConeStacked:            15,
		Bar3DConePercentStacked:     15,
		Bar3DPyramidClustered:       15,
		Bar3DPyramidStacked:         15,
		Bar3DPyramidPercentStacked:  15,
		Bar3DCylinderClustered:      15,
		Bar3DCylinderStacked:        15,
		Bar3DCylinderPercentStacked: 15,
		Col:                         0,
		ColStacked:                  0,
		ColPercentStacked:           0,
		Col3D:                       15,
		Col3DClustered:              15,
		Col3DStacked:                15,
		Col3DPercentStacked:         15,
		Col3DCone:                   15,
		Col3DConeClustered:          15,
		Col3DConeStacked:            15,
		Col3DConePercentStacked:     15,
		Col3DPyramid:                15,
		Col3DPyramidClustered:       15,
		Col3DPyramidStacked:         15,
		Col3DPyramidPercentStacked:  15,
		Col3DCylinder:               15,
		Col3DCylinderClustered:      15,
		Col3DCylinderStacked:        15,
		Col3DCylinderPercentStacked: 15,
		Doughnut:                    0,
		Line:                        0,
		Line3D:                      20,
		Pie:                         0,
		Pie3D:                       30,
		PieOfPie:                    0,
		BarOfPie:                    0,
		Radar:                       0,
		Scatter:                     0,
		Surface3D:                   15,
		WireframeSurface3D:          15,
		Contour:                     90,
		WireframeContour:            90,
	}
	chartView3DRotY = map[ChartType]int{
		Area:                        0,
		AreaStacked:                 0,
		AreaPercentStacked:          0,
		Area3D:                      20,
		Area3DStacked:               20,
		Area3DPercentStacked:        20,
		Bar:                         0,
		BarStacked:                  0,
		BarPercentStacked:           0,
		Bar3DClustered:              20,
		Bar3DStacked:                20,
		Bar3DPercentStacked:         20,
		Bar3DConeClustered:          20,
		Bar3DConeStacked:            20,
		Bar3DConePercentStacked:     20,
		Bar3DPyramidClustered:       20,
		Bar3DPyramidStacked:         20,
		Bar3DPyramidPercentStacked:  20,
		Bar3DCylinderClustered:      20,
		Bar3DCylinderStacked:        20,
		Bar3DCylinderPercentStacked: 20,
		Col:                         0,
		ColStacked:                  0,
		ColPercentStacked:           0,
		Col3D:                       20,
		Col3DClustered:              20,
		Col3DStacked:                20,
		Col3DPercentStacked:         20,
		Col3DCone:                   20,
		Col3DConeClustered:          20,
		Col3DConeStacked:            20,
		Col3DConePercentStacked:     20,
		Col3DPyramid:                20,
		Col3DPyramidClustered:       20,
		Col3DPyramidStacked:         20,
		Col3DPyramidPercentStacked:  20,
		Col3DCylinder:               20,
		Col3DCylinderClustered:      20,
		Col3DCylinderStacked:        20,
		Col3DCylinderPercentStacked: 20,
		Doughnut:                    0,
		Line:                        0,
		Line3D:                      15,
		Pie:                         0,
		Pie3D:                       0,
		PieOfPie:                    0,
		BarOfPie:                    0,
		Radar:                       0,
		Scatter:                     0,
		Surface3D:                   20,
		WireframeSurface3D:          20,
		Contour:                     0,
		WireframeContour:            0,
	}
	plotAreaChartOverlap = map[ChartType]int{
		BarStacked:        100,
		BarPercentStacked: 100,
		ColStacked:        100,
		ColPercentStacked: 100,
	}
	chartView3DPerspective = map[ChartType]int{
		Line3D:           30,
		Contour:          0,
		WireframeContour: 0,
	}
	chartView3DRAngAx = map[ChartType]int{
		Area:                        0,
		AreaStacked:                 0,
		AreaPercentStacked:          0,
		Area3D:                      1,
		Area3DStacked:               1,
		Area3DPercentStacked:        1,
		Bar:                         0,
		BarStacked:                  0,
		BarPercentStacked:           0,
		Bar3DClustered:              1,
		Bar3DStacked:                1,
		Bar3DPercentStacked:         1,
		Bar3DConeClustered:          1,
		Bar3DConeStacked:            1,
		Bar3DConePercentStacked:     1,
		Bar3DPyramidClustered:       1,
		Bar3DPyramidStacked:         1,
		Bar3DPyramidPercentStacked:  1,
		Bar3DCylinderClustered:      1,
		Bar3DCylinderStacked:        1,
		Bar3DCylinderPercentStacked: 1,
		Col:                         0,
		ColStacked:                  0,
		ColPercentStacked:           0,
		Col3D:                       1,
		Col3DClustered:              1,
		Col3DStacked:                1,
		Col3DPercentStacked:         1,
		Col3DCone:                   1,
		Col3DConeClustered:          1,
		Col3DConeStacked:            1,
		Col3DConePercentStacked:     1,
		Col3DPyramid:                1,
		Col3DPyramidClustered:       1,
		Col3DPyramidStacked:         1,
		Col3DPyramidPercentStacked:  1,
		Col3DCylinder:               1,
		Col3DCylinderClustered:      1,
		Col3DCylinderStacked:        1,
		Col3DCylinderPercentStacked: 1,
		Doughnut:                    0,
		Line:                        0,
		Line3D:                      0,
		Pie:                         0,
		Pie3D:                       0,
		PieOfPie:                    0,
		BarOfPie:                    0,
		Radar:                       0,
		Scatter:                     0,
		Surface3D:                   0,
		WireframeSurface3D:          0,
		Contour:                     0,
		Bubble:                      0,
		Bubble3D:                    0,
	}
	chartLegendPosition = map[string]string{
		"bottom":    "b",
		"left":      "l",
		"right":     "r",
		"top":       "t",
		"top_right": "tr",
	}
	chartValAxNumFmtFormatCode = map[ChartType]string{
		Area:                        "General",
		AreaStacked:                 "General",
		AreaPercentStacked:          "0%",
		Area3D:                      "General",
		Area3DStacked:               "General",
		Area3DPercentStacked:        "0%",
		Bar:                         "General",
		BarStacked:                  "General",
		BarPercentStacked:           "0%",
		Bar3DClustered:              "General",
		Bar3DStacked:                "General",
		Bar3DPercentStacked:         "0%",
		Bar3DConeClustered:          "General",
		Bar3DConeStacked:            "General",
		Bar3DConePercentStacked:     "0%",
		Bar3DPyramidClustered:       "General",
		Bar3DPyramidStacked:         "General",
		Bar3DPyramidPercentStacked:  "0%",
		Bar3DCylinderClustered:      "General",
		Bar3DCylinderStacked:        "General",
		Bar3DCylinderPercentStacked: "0%",
		Col:                         "General",
		ColStacked:                  "General",
		ColPercentStacked:           "0%",
		Col3D:                       "General",
		Col3DClustered:              "General",
		Col3DStacked:                "General",
		Col3DPercentStacked:         "0%",
		Col3DCone:                   "General",
		Col3DConeClustered:          "General",
		Col3DConeStacked:            "General",
		Col3DConePercentStacked:     "0%",
		Col3DPyramid:                "General",
		Col3DPyramidClustered:       "General",
		Col3DPyramidStacked:         "General",
		Col3DPyramidPercentStacked:  "0%",
		Col3DCylinder:               "General",
		Col3DCylinderClustered:      "General",
		Col3DCylinderStacked:        "General",
		Col3DCylinderPercentStacked: "0%",
		Doughnut:                    "General",
		Line:                        "General",
		Line3D:                      "General",
		Pie:                         "General",
		Pie3D:                       "General",
		PieOfPie:                    "General",
		BarOfPie:                    "General",
		Radar:                       "General",
		Scatter:                     "General",
		Surface3D:                   "General",
		WireframeSurface3D:          "General",
		Contour:                     "General",
		WireframeContour:            "General",
		Bubble:                      "General",
		Bubble3D:                    "General",
		StockHighLowClose:           "General",
		StockOpenHighLowClose:       "General",
	}
	chartValAxCrossBetween = map[ChartType]string{
		Area:                        "midCat",
		AreaStacked:                 "midCat",
		AreaPercentStacked:          "midCat",
		Area3D:                      "midCat",
		Area3DStacked:               "midCat",
		Area3DPercentStacked:        "midCat",
		Bar:                         "between",
		BarStacked:                  "between",
		BarPercentStacked:           "between",
		Bar3DClustered:              "between",
		Bar3DStacked:                "between",
		Bar3DPercentStacked:         "between",
		Bar3DConeClustered:          "between",
		Bar3DConeStacked:            "between",
		Bar3DConePercentStacked:     "between",
		Bar3DPyramidClustered:       "between",
		Bar3DPyramidStacked:         "between",
		Bar3DPyramidPercentStacked:  "between",
		Bar3DCylinderClustered:      "between",
		Bar3DCylinderStacked:        "between",
		Bar3DCylinderPercentStacked: "between",
		Col:                         "between",
		ColStacked:                  "between",
		ColPercentStacked:           "between",
		Col3D:                       "between",
		Col3DClustered:              "between",
		Col3DStacked:                "between",
		Col3DPercentStacked:         "between",
		Col3DCone:                   "between",
		Col3DConeClustered:          "between",
		Col3DConeStacked:            "between",
		Col3DConePercentStacked:     "between",
		Col3DPyramid:                "between",
		Col3DPyramidClustered:       "between",
		Col3DPyramidStacked:         "between",
		Col3DPyramidPercentStacked:  "between",
		Col3DCylinder:               "between",
		Col3DCylinderClustered:      "between",
		Col3DCylinderStacked:        "between",
		Col3DCylinderPercentStacked: "between",
		Doughnut:                    "between",
		Line:                        "between",
		Line3D:                      "between",
		Pie:                         "between",
		Pie3D:                       "between",
		PieOfPie:                    "between",
		BarOfPie:                    "between",
		Radar:                       "between",
		Scatter:                     "between",
		Surface3D:                   "midCat",
		WireframeSurface3D:          "midCat",
		Contour:                     "midCat",
		WireframeContour:            "midCat",
		Bubble:                      "midCat",
		Bubble3D:                    "midCat",
		StockHighLowClose:           "between",
		StockOpenHighLowClose:       "between",
	}
	plotAreaChartGrouping = map[ChartType]string{
		Area:                        "standard",
		AreaStacked:                 "stacked",
		AreaPercentStacked:          "percentStacked",
		Area3D:                      "standard",
		Area3DStacked:               "stacked",
		Area3DPercentStacked:        "percentStacked",
		Bar:                         "clustered",
		BarStacked:                  "stacked",
		BarPercentStacked:           "percentStacked",
		Bar3DClustered:              "clustered",
		Bar3DStacked:                "stacked",
		Bar3DPercentStacked:         "percentStacked",
		Bar3DConeClustered:          "clustered",
		Bar3DConeStacked:            "stacked",
		Bar3DConePercentStacked:     "percentStacked",
		Bar3DPyramidClustered:       "clustered",
		Bar3DPyramidStacked:         "stacked",
		Bar3DPyramidPercentStacked:  "percentStacked",
		Bar3DCylinderClustered:      "clustered",
		Bar3DCylinderStacked:        "stacked",
		Bar3DCylinderPercentStacked: "percentStacked",
		Col:                         "clustered",
		ColStacked:                  "stacked",
		ColPercentStacked:           "percentStacked",
		Col3D:                       "standard",
		Col3DClustered:              "clustered",
		Col3DStacked:                "stacked",
		Col3DPercentStacked:         "percentStacked",
		Col3DCone:                   "standard",
		Col3DConeClustered:          "clustered",
		Col3DConeStacked:            "stacked",
		Col3DConePercentStacked:     "percentStacked",
		Col3DPyramid:                "standard",
		Col3DPyramidClustered:       "clustered",
		Col3DPyramidStacked:         "stacked",
		Col3DPyramidPercentStacked:  "percentStacked",
		Col3DCylinder:               "standard",
		Col3DCylinderClustered:      "clustered",
		Col3DCylinderStacked:        "stacked",
		Col3DCylinderPercentStacked: "percentStacked",
		Line:                        "standard",
		Line3D:                      "standard",
	}
	plotAreaChartBarDir = map[ChartType]string{
		Bar:                         "bar",
		BarStacked:                  "bar",
		BarPercentStacked:           "bar",
		Bar3DClustered:              "bar",
		Bar3DStacked:                "bar",
		Bar3DPercentStacked:         "bar",
		Bar3DConeClustered:          "bar",
		Bar3DConeStacked:            "bar",
		Bar3DConePercentStacked:     "bar",
		Bar3DPyramidClustered:       "bar",
		Bar3DPyramidStacked:         "bar",
		Bar3DPyramidPercentStacked:  "bar",
		Bar3DCylinderClustered:      "bar",
		Bar3DCylinderStacked:        "bar",
		Bar3DCylinderPercentStacked: "bar",
		Col:                         "col",
		ColStacked:                  "col",
		ColPercentStacked:           "col",
		Col3D:                       "col",
		Col3DClustered:              "col",
		Col3DStacked:                "col",
		Col3DPercentStacked:         "col",
		Col3DCone:                   "col",
		Col3DConeStacked:            "col",
		Col3DConeClustered:          "col",
		Col3DConePercentStacked:     "col",
		Col3DPyramid:                "col",
		Col3DPyramidClustered:       "col",
		Col3DPyramidStacked:         "col",
		Col3DPyramidPercentStacked:  "col",
		Col3DCylinder:               "col",
		Col3DCylinderClustered:      "col",
		Col3DCylinderStacked:        "col",
		Col3DCylinderPercentStacked: "col",
		Line:                        "standard",
		Line3D:                      "standard",
	}
	barColChartTypes = []ChartType{
		Bar,
		BarStacked,
		BarPercentStacked,
		Bar3DClustered,
		Bar3DStacked,
		Bar3DPercentStacked,
		Bar3DConeClustered,
		Bar3DConeStacked,
		Bar3DConePercentStacked,
		Bar3DPyramidClustered,
		Bar3DPyramidStacked,
		Bar3DPyramidPercentStacked,
		Bar3DCylinderClustered,
		Bar3DCylinderStacked,
		Bar3DCylinderPercentStacked,
		Col,
		ColStacked,
		ColPercentStacked,
		Col3D,
		Col3DClustered,
		Col3DStacked,
		Col3DPercentStacked,
		Col3DCone,
		Col3DConeStacked,
		Col3DConeClustered,
		Col3DConePercentStacked,
		Col3DPyramid,
		Col3DPyramidClustered,
		Col3DPyramidStacked,
		Col3DPyramidPercentStacked,
		Col3DCylinder,
		Col3DCylinderClustered,
		Col3DCylinderStacked,
		Col3DCylinderPercentStacked,
	}
	orientation = map[bool]string{
		true:  "maxMin",
		false: "minMax",
	}
	catAxPos = map[bool]string{
		true:  "t",
		false: "b",
	}
	valAxPos = map[bool]string{
		true:  "r",
		false: "l",
	}
	tickLblPosVal = map[ChartTickLabelPositionType]string{
		ChartTickLabelNextToAxis: "nextTo",
		ChartTickLabelHigh:       "high",
		ChartTickLabelLow:        "low",
		ChartTickLabelNone:       "none",
	}
	tickLblPosNone = map[ChartType]string{
		Contour:          "none",
		WireframeContour: "none",
	}
	chartTickMarkTypes = map[ChartTickMarkType]string{
		ChartTickMarkNone:    "none",
		ChartTickMarkInside:  "in",
		ChartTickMarkOutside: "out",
		ChartTickMarkCross:   "cross",
	}
)

// parseChartOptions provides a function to parse the format settings of the
// chart with default value.
func parseChartOptions(opts *Chart) (*Chart, error) {
	if opts == nil {
		return nil, ErrParameterInvalid
	}
	if opts.Dimension.Width == 0 {
		opts.Dimension.Width = defaultChartDimensionWidth
	}
	if opts.Dimension.Height == 0 {
		opts.Dimension.Height = defaultChartDimensionHeight
	}
	if opts.Format.PrintObject == nil {
		opts.Format.PrintObject = boolPtr(true)
	}
	if opts.Format.Locked == nil {
		opts.Format.Locked = boolPtr(false)
	}
	if opts.Format.ScaleX == 0 {
		opts.Format.ScaleX = defaultDrawingScale
	}
	if opts.Format.ScaleY == 0 {
		opts.Format.ScaleY = defaultDrawingScale
	}
	if opts.Legend.Position == "" {
		opts.Legend.Position = defaultChartLegendPosition
	}
	opts.parseTitle()
	if opts.Fill.Transparency < 0 || 100 < opts.Fill.Transparency {
		return opts, ErrTransparency
	}
	if opts.VaryColors == nil {
		opts.VaryColors = boolPtr(true)
	}
	if opts.Border.Width == 0 {
		opts.Border.Width = 0.75
	}
	if opts.ShowBlanksAs == "" {
		opts.ShowBlanksAs = defaultChartShowBlanksAs
	}
	return opts, opts.parseSeries()
}

// parseSeries check the series settings of the chart.
func (opts *Chart) parseSeries() error {
	for _, series := range opts.Series {
		if series.Fill.Transparency < 0 || 100 < series.Fill.Transparency {
			return ErrTransparency
		}
	}
	return nil
}

// parseTitle parse the title settings of the chart with default value.
func (opts *Chart) parseTitle() {
	for i := range opts.Title {
		if opts.Title[i].Font == nil {
			opts.Title[i].Font = &Font{}
		}
		if opts.Title[i].Font.Color == "" {
			opts.Title[i].Font.Color = "595959"
		}
		if opts.Title[i].Font.Size == 0 {
			opts.Title[i].Font.Size = 14
		}
	}
}

// AddChart provides the method to add chart in a sheet by given chart format
// set (such as offset, scale, aspect ratio setting and print settings) and
// properties set. For example, create 3D clustered column chart with data
// Sheet1!$E$1:$L$15:
//
//	package main
//
//	import (
//	    "fmt"
//
//	    "github.com/debugdoctor/excelize-plus/v2"
//	)
//
//	func main() {
//	    f := excelize.NewFile()
//	    defer func() {
//	        if err := f.Close(); err != nil {
//	            fmt.Println(err)
//	        }
//	    }()
//	    for idx, row := range [][]interface{}{
//	        {nil, "Apple", "Orange", "Pear"}, {"Small", 2, 3, 3},
//	        {"Normal", 5, 2, 4}, {"Large", 6, 7, 8},
//	    } {
//	        cell, err := excelize.CoordinatesToCellName(1, idx+1)
//	        if err != nil {
//	            fmt.Println(err)
//	            return
//	        }
//	        f.SetSheetRow("Sheet1", cell, &row)
//	    }
//	    if err := f.AddChart("Sheet1", "E1", &excelize.Chart{
//	        Type: excelize.Col3DClustered,
//	        Series: []excelize.ChartSeries{
//	            {
//	                Name:       "Sheet1!$A$2",
//	                Categories: "Sheet1!$B$1:$D$1",
//	                Values:     "Sheet1!$B$2:$D$2",
//	            },
//	            {
//	                Name:       "Sheet1!$A$3",
//	                Categories: "Sheet1!$B$1:$D$1",
//	                Values:     "Sheet1!$B$3:$D$3",
//	            },
//	            {
//	                Name:       "Sheet1!$A$4",
//	                Categories: "Sheet1!$B$1:$D$1",
//	                Values:     "Sheet1!$B$4:$D$4",
//	            },
//	        },
//	        Title: []excelize.RichTextRun{
//	            {
//	                Text: "Fruit 3D Clustered Column Chart",
//	            },
//	        },
//	        Legend: excelize.ChartLegend{
//	            ShowLegendKey: false,
//	        },
//	        PlotArea: excelize.ChartPlotArea{
//	            ShowBubbleSize:  true,
//	            ShowCatName:     false,
//	            ShowLeaderLines: false,
//	            ShowPercent:     true,
//	            ShowSerName:     true,
//	            ShowVal:         true,
//	        },
//	    }); err != nil {
//	        fmt.Println(err)
//	        return
//	    }
//	    // Save spreadsheet by the given path.
//	    if err := f.SaveAs("Book1.xlsx"); err != nil {
//	        fmt.Println(err)
//	    }
//	}
//
// The following shows the type of chart supported by excelize:
//
//	 ID | Enumeration                 | Chart
//	----+-----------------------------+------------------------------
//	 0  | Area                        | 2D area chart
//	 1  | AreaStacked                 | 2D stacked area chart
//	 2  | AreaPercentStacked          | 2D 100% stacked area chart
//	 3  | Area3D                      | 3D area chart
//	 4  | Area3DStacked               | 3D stacked area chart
//	 5  | Area3DPercentStacked        | 3D 100% stacked area chart
//	 6  | Bar                         | 2D clustered bar chart
//	 7  | BarStacked                  | 2D stacked bar chart
//	 8  | BarPercentStacked           | 2D 100% stacked bar chart
//	 9  | Bar3DClustered              | 3D clustered bar chart
//	 10 | Bar3DStacked                | 3D stacked bar chart
//	 11 | Bar3DPercentStacked         | 3D 100% stacked bar chart
//	 12 | Bar3DConeClustered          | 3D cone clustered bar chart
//	 13 | Bar3DConeStacked            | 3D cone stacked bar chart
//	 14 | Bar3DConePercentStacked     | 3D cone percent bar chart
//	 15 | Bar3DPyramidClustered       | 3D pyramid clustered bar chart
//	 16 | Bar3DPyramidStacked         | 3D pyramid stacked bar chart
//	 17 | Bar3DPyramidPercentStacked  | 3D pyramid percent stacked bar chart
//	 18 | Bar3DCylinderClustered      | 3D cylinder clustered bar chart
//	 19 | Bar3DCylinderStacked        | 3D cylinder stacked bar chart
//	 20 | Bar3DCylinderPercentStacked | 3D cylinder percent stacked bar chart
//	 21 | Col                         | 2D clustered column chart
//	 22 | ColStacked                  | 2D stacked column chart
//	 23 | ColPercentStacked           | 2D 100% stacked column chart
//	 24 | Col3DClustered              | 3D clustered column chart
//	 25 | Col3D                       | 3D column chart
//	 26 | Col3DStacked                | 3D stacked column chart
//	 27 | Col3DPercentStacked         | 3D 100% stacked column chart
//	 28 | Col3DCone                   | 3D cone column chart
//	 29 | Col3DConeClustered          | 3D cone clustered column chart
//	 30 | Col3DConeStacked            | 3D cone stacked column chart
//	 31 | Col3DConePercentStacked     | 3D cone percent stacked column chart
//	 32 | Col3DPyramid                | 3D pyramid column chart
//	 33 | Col3DPyramidClustered       | 3D pyramid clustered column chart
//	 34 | Col3DPyramidStacked         | 3D pyramid stacked column chart
//	 35 | Col3DPyramidPercentStacked  | 3D pyramid percent stacked column chart
//	 36 | Col3DCylinder               | 3D cylinder column chart
//	 37 | Col3DCylinderClustered      | 3D cylinder clustered column chart
//	 38 | Col3DCylinderStacked        | 3D cylinder stacked column chart
//	 39 | Col3DCylinderPercentStacked | 3D cylinder percent stacked column chart
//	 40 | Doughnut                    | doughnut chart
//	 41 | Line                        | line chart
//	 42 | Line3D                      | 3D line chart
//	 43 | Pie                         | pie chart
//	 44 | Pie3D                       | 3D pie chart
//	 45 | PieOfPie                    | pie of pie chart
//	 46 | BarOfPie                    | bar of pie chart
//	 47 | Radar                       | radar chart
//	 48 | Scatter                     | scatter chart
//	 49 | Surface3D                   | 3D surface chart
//	 50 | WireframeSurface3D          | 3D wireframe surface chart
//	 51 | Contour                     | contour chart
//	 52 | WireframeContour            | wireframe contour chart
//	 53 | Bubble                      | bubble chart
//	 54 | Bubble3D                    | 3D bubble chart
//	 55 | StockHighLowClose           | High-Low-Close stock chart
//	 56 | StockOpenHighLowClose       | Open-High-Low-Close stock chart
//
// In Excel a chart series is a collection of information that defines which
// data is plotted such as values, axis labels and formatting.
//
// The series options that can be set are:
//
//	Name
//	Categories
//	Values
//	Fill
//	Legend
//	Line
//	Marker
//	DataLabel
//	DataLabelPosition
//
// Name: Set the name for the series. The name is displayed in the chart legend
// and in the formula bar. The 'Name' property is optional and if it isn't
// supplied it will default to Series 1..n. The name can also be a formula such
// as Sheet1!$A$1
//
// Categories: This sets the chart category labels. The category is more or less
// the same as the X axis. In most chart types the 'Categories' property is
// optional and the chart will just assume a sequential series from 1..n.
//
// Values: This is the most important property of a series and is the only
// mandatory option for every chart object. This option links the chart with
// the worksheet data that it displays.
//
// Sizes: This sets the bubble size in a data series. The 'Sizes' property is
// optional and the default value was same with 'Values'.
//
// Fill: This set the format for the data series fill. The 'Fill' property is
// optional.
//
// Legend: This set the font of legend text for a data series. The 'Legend'
// property is optional.
//
// Line: This sets the line format of the line chart. The 'Line' property is
// optional and if it isn't supplied it will default style. The options that
// can be set are width and color. The range of width is 0.25pt - 999pt. If the
// value of width is outside the range, the default width of the line is 2pt.
//
// Marker: This sets the marker of the line chart and scatter chart. The range
// of optional field 'Size' is 2-72 (default value is 5). The enumeration value
// of optional field 'Symbol' are (default value is 'auto'):
//
//	circle
//	dash
//	diamond
//	dot
//	none
//	picture
//	plus
//	square
//	star
//	triangle
//	x
//	auto
//
// DataLabel: This sets the format of the chart series data label.
//
// DataLabelPosition: This sets the position of the chart series data label.
//
// Set properties of the chart legend. The options that can be set are:
//
//	Position
//	ShowLegendKey
//	Font
//
// Position: Set the position of the chart legend. The default legend position
// is bottom. The available positions are:
//
//	none
//	top
//	bottom
//	left
//	right
//	top_right
//
// ShowLegendKey: Set the legend keys shall be shown in data labels. The default
// value is false.
//
// Font: Set the font properties of the chart legend text. The properties that
// can be set are the same as the font object that is used for cell formatting.
// The font family, size, color, bold, italic, underline, and strike properties
// can be set.
//
// Set properties of the chart title. The properties that can be set are:
//
//	Title
//
// Title: Set the name (title) for the chart. The name is displayed above the
// chart. The name can also be a formula such as Sheet1!$A$1 or a list with a
// sheet name. The name property is optional. The default is to have no chart
// title.
//
// Specifies how blank cells are plotted on the chart by 'ShowBlanksAs'. The
// default value is gap. The options that can be set are:
//
//	gap
//	span
//	zero
//
// gap: Specifies that blank values shall be left as a gap.
//
// span: Specifies that blank values shall be spanned with a line.
//
// zero: Specifies that blank values shall be treated as zero.
//
// Specifies that each data marker in the series has a different color by
// 'VaryColors'. The default value is true.
//
// Set chart offset, scale, aspect ratio setting and print settings by 'Format',
// same as function 'AddPicture'.
//
// Set the position of the chart plot area by 'PlotArea'. The properties that
// can be set are:
//
//	SecondPlotValues
//	ShowBubbleSize
//	ShowCatName
//	ShowDataTable
//	ShowDataTableKeys
//	ShowLeaderLines
//	ShowPercent
//	ShowSerName
//	ShowVal
//	Fill
//	UpBars
//	DownBars
//	NumFmt
//
// SecondPlotValues: Specifies the values in second plot for the 'PieOfPie' and
// 'BarOfPie' chart.
//
// ShowBubbleSize: Specifies the bubble size shall be shown in a data label. The
// 'ShowBubbleSize' property is optional. The default value is false.
//
// ShowCatName: Specifies that the category name shall be shown in the data
// label. The 'ShowCatName' property is optional. The default value is true.
//
// ShowDataTable: Used for add data table under chart, depending on the chart
// type, only available for area, bar, column and line series type charts. The
// 'ShowDataTable' property is optional. The default value is false.
//
// ShowDataTableKeys: Used for add legend key in data table, only works on
// 'ShowDataTable' is enabled. The 'ShowDataTableKeys' property is optional.
// The default value is false.
//
// ShowLeaderLines: Specifies leader lines shall be shown for data labels. The
// 'ShowLeaderLines' property is optional. The default value is false.
//
// ShowPercent: Specifies that the percentage shall be shown in a data label.
// The 'ShowPercent' property is optional. The default value is false.
//
// ShowSerName: Specifies that the series name shall be shown in a data label.
// The 'ShowSerName' property is optional. The default value is false.
//
// ShowVal: Specifies that the value shall be shown in a data label.
// The 'ShowVal' property is optional. The default value is false.
//
// Fill: Set fill color of the chart.
//
// UpBars: Specifies the format for stock chart up bars. The 'UpBars' property
// is optional.
//
// DownBars: Specifies the format for stock chart down bars. The 'DownBars'
// property is optional.
//
// NumFmt: Specifies that if linked to source and set custom number format code
// for data labels. The 'NumFmt' property is optional. The default format code
// is 'General'.
//
// Set the primary horizontal and vertical axis options by 'XAxis' and 'YAxis'.
// The properties of 'XAxis' that can be set are:
//
//	None
//	MajorGridLines
//	MinorGridLines
//	TickLabelSkip
//	ReverseOrder
//	Maximum
//	Minimum
//	Alignment
//	Font
//	NumFmt
//	Title
//
// The properties of 'YAxis' that can be set are:
//
//	None
//	MajorGridLines
//	MinorGridLines
//	MajorUnit
//	Secondary
//	ReverseOrder
//	Maximum
//	Minimum
//	Alignment
//	Font
//	LogBase
//	NumFmt
//	Title
//
// None: Disable axes.
//
// MajorGridLines: Specifies major grid lines.
//
// MinorGridLines: Specifies minor grid lines.
//
// MajorUnit: Specifies the distance between major ticks. Shall contain a
// positive floating-point number. The 'MajorUnit' property is optional. The
// default value is auto.
//
// Secondary: Specifies the current series vertical axis as the secondary axis,
// this only works for the second and later chart in the combo chart. The
// default value is false.
//
// TickLabelSkip: Specifies how many tick labels to skip between label that is
// drawn. The 'TickLabelSkip' property is optional. The default value is auto.
//
// ReverseOrder: Specifies that the categories or values on reverse order
// (orientation of the chart). The 'ReverseOrder' property is optional. The
// default value is false.
//
// Maximum: Specifies that the fixed maximum, 0 is auto. The 'Maximum' property
// is optional. The default value is auto.
//
// Minimum: Specifies that the fixed minimum, 0 is auto. The 'Minimum' property
// is optional. The default value is auto.
//
// Alignment: Specifies that the alignment of the horizontal and vertical axis.
// The properties of alignment that can be set are:
//
//	TextRotation
//	Vertical
//
// The value of 'TextRotation' that can be set from -90 to 90.
//
// The value of 'Vertical' that can be set are:
//
//	horz
//	vert
//	vert270
//	wordArtVert
//	eaVert
//	mongolianVert
//	wordArtVertRtl
//
// Font: Specifies that the font of the horizontal and vertical axis. The
// properties of font that can be set are:
//
//	Bold
//	Italic
//	Underline
//	Family
//	Size
//	Strike
//	Color
//	VertAlign
//
// LogBase: Specifies logarithmic scale base number of the vertical axis.
//
// NumFmt: Specifies that if linked to source and set custom number format code
// for axis. The 'NumFmt' property is optional. The default format code is
// 'General'.
//
// Title: Specifies that the primary horizontal or vertical axis title and
// resize chart. The 'Title' property is optional.
//
// Set chart size by 'Dimension' property. The 'Dimension' property is optional.
// The default width is 480, and height is 260.
//
// Set chart legend for all data series by 'Legend' property. The 'Legend'
// property is optional.
//
// Set the bubble size in all data series for the bubble chart or 3D bubble
// chart by 'BubbleSizes' property. The 'BubbleSizes' property is optional. The
// default width is 100, and the value should be great than 0 and less or equal
// than 300.
//
// Set the doughnut hole size in all data series for the doughnut chart by
// 'HoleSize' property. The 'HoleSize' property is optional. The default width
// is 75, and the value should be great than 0 and less or equal than 90.
//
// Set the gap with of the column and bar series chart by 'GapWidth' property.
// The 'GapWidth' property is optional. The default width is 150, and the value
// should be great or equal than 0 and less or equal than 500.
//
// Set series overlap of the column and bar series chart by 'Overlap' property.
// The 'Overlap' property is optional. The default width is 0, and the value
// should be great or equal than -100 and less or equal than 100.
//
// combo: Specifies the create a chart that combines two or more chart types in
// a single chart. For example, create a clustered column - line chart with
// data Sheet1!$E$1:$L$15:
//
//	package main
//
//	import (
//	    "fmt"
//
//	    "github.com/debugdoctor/excelize-plus/v2"
//	)
//
//	func main() {
//	    f := excelize.NewFile()
//	    defer func() {
//	        if err := f.Close(); err != nil {
//	            fmt.Println(err)
//	        }
//	    }()
//	    for idx, row := range [][]interface{}{
//	        {nil, "Apple", "Orange", "Pear"}, {"Small", 2, 3, 3},
//	        {"Normal", 5, 2, 4}, {"Large", 6, 7, 8},
//	    } {
//	        cell, err := excelize.CoordinatesToCellName(1, idx+1)
//	        if err != nil {
//	            fmt.Println(err)
//	            return
//	        }
//	        f.SetSheetRow("Sheet1", cell, &row)
//	    }
//	    enable, disable := true, false
//	    if err := f.AddChart("Sheet1", "E1", &excelize.Chart{
//	        Type: excelize.Col,
//	        Series: []excelize.ChartSeries{
//	            {
//	                Name:       "Sheet1!$A$2",
//	                Categories: "Sheet1!$B$1:$D$1",
//	                Values:     "Sheet1!$B$2:$D$2",
//	            },
//	        },
//	        Format: excelize.GraphicOptions{
//	            ScaleX:          1,
//	            ScaleY:          1,
//	            OffsetX:         15,
//	            OffsetY:         10,
//	            PrintObject:     &enable,
//	            LockAspectRatio: false,
//	            Locked:          &disable,
//	        },
//	        Title: []excelize.RichTextRun{
//	            {
//	                Text: "Clustered Column - Line Chart",
//	            },
//	        },
//	        Legend: excelize.ChartLegend{
//	            Position:      "left",
//	            ShowLegendKey: false,
//	        },
//	        PlotArea: excelize.ChartPlotArea{
//	            ShowCatName:     false,
//	            ShowLeaderLines: false,
//	            ShowPercent:     true,
//	            ShowSerName:     true,
//	            ShowVal:         true,
//	        },
//	    }, &excelize.Chart{
//	        Type: excelize.Line,
//	        Series: []excelize.ChartSeries{
//	            {
//	                Name:       "Sheet1!$A$4",
//	                Categories: "Sheet1!$B$1:$D$1",
//	                Values:     "Sheet1!$B$4:$D$4",
//	                Marker: excelize.ChartMarker{
//	                    Symbol: "none", Size: 10,
//	                },
//	            },
//	        },
//	        Format: excelize.GraphicOptions{
//	            ScaleX:          1,
//	            ScaleY:          1,
//	            OffsetX:         15,
//	            OffsetY:         10,
//	            PrintObject:     &enable,
//	            LockAspectRatio: false,
//	            Locked:          &disable,
//	        },
//	        Legend: excelize.ChartLegend{
//	            Position:      "right",
//	            ShowLegendKey: false,
//	        },
//	        PlotArea: excelize.ChartPlotArea{
//	            ShowCatName:     false,
//	            ShowLeaderLines: false,
//	            ShowPercent:     true,
//	            ShowSerName:     true,
//	            ShowVal:         true,
//	        },
//	    }); err != nil {
//	        fmt.Println(err)
//	        return
//	    }
//	    // Save spreadsheet by the given path.
//	    if err := f.SaveAs("Book1.xlsx"); err != nil {
//	        fmt.Println(err)
//	    }
//	}
func (f *File) AddChart(sheet, cell string, chart *Chart, combo ...*Chart) error {
	// Read worksheet data
	ws, err := f.workSheetReader(sheet)
	if err != nil {
		return err
	}
	opts, comboCharts, err := f.getChartOptions(chart, combo)
	if err != nil {
		return err
	}
	// Add first picture for given sheet, create xl/drawings/ and xl/drawings/_rels/ folder.
	drawingID := f.countDrawings() + 1
	chartID := f.countCharts() + 1
	drawingXML := "xl/drawings/drawing" + strconv.Itoa(drawingID) + ".xml"
	drawingID, drawingXML = f.prepareDrawing(ws, drawingID, sheet, drawingXML)
	drawingRels := "xl/drawings/_rels/drawing" + strconv.Itoa(drawingID) + ".xml.rels"
	drawingRID := f.addRels(drawingRels, SourceRelationshipChart, "../charts/chart"+strconv.Itoa(chartID)+".xml", "")
	err = f.addDrawingChart(sheet, drawingXML, cell, int(opts.Dimension.Width), int(opts.Dimension.Height), drawingRID, &opts.Format)
	if err != nil {
		return err
	}
	f.addChart(opts, comboCharts)
	if err = f.addContentTypePart(chartID, "chart"); err != nil {
		return err
	}
	_ = f.addContentTypePart(drawingID, "drawings")
	f.addSheetNameSpace(sheet, SourceRelationship)
	return err
}

// AddChartWithPosition provides the method to add a chart in a sheet using
// an exact ChartPosition (From/To with EMU offsets) instead of calculating
// from cell + dimension. The cell parameter is used only to locate the
// drawing relationship; the actual anchor position comes from chart.Position.
// If chart.Position is nil, it falls back to the same behavior as AddChart.
func (f *File) AddChartWithPosition(sheet, cell string, chart *Chart, combo ...*Chart) error {
	if chart.Position == nil {
		return f.AddChart(sheet, cell, chart, combo...)
	}
	ws, err := f.workSheetReader(sheet)
	if err != nil {
		return err
	}
	opts, comboCharts, err := f.getChartOptions(chart, combo)
	if err != nil {
		return err
	}
	drawingID := f.countDrawings() + 1
	chartID := f.countCharts() + 1
	drawingXML := "xl/drawings/drawing" + strconv.Itoa(drawingID) + ".xml"
	drawingID, drawingXML = f.prepareDrawing(ws, drawingID, sheet, drawingXML)
	drawingRels := "xl/drawings/_rels/drawing" + strconv.Itoa(drawingID) + ".xml.rels"
	drawingRID := f.addRels(drawingRels, SourceRelationshipChart, "../charts/chart"+strconv.Itoa(chartID)+".xml", "")
	if err = f.addDrawingChartWithPosition(drawingXML, opts.Position, drawingRID, &opts.Format); err != nil {
		return err
	}
	f.addChart(opts, comboCharts)
	if err = f.addContentTypePart(chartID, "chart"); err != nil {
		return err
	}
	_ = f.addContentTypePart(drawingID, "drawings")
	f.addSheetNameSpace(sheet, SourceRelationship)
	return err
}

// AddChartSheet provides the method to create a chartsheet by given chart
// format set (such as offset, scale, aspect ratio setting and print settings)
// and properties set. In Excel a chartsheet is a worksheet that only contains
// a chart.
func (f *File) AddChartSheet(sheet string, chart *Chart, combo ...*Chart) error {
	// Check if the worksheet already exists
	idx, err := f.GetSheetIndex(sheet)
	if err != nil {
		return err
	}
	if idx != -1 {
		return ErrExistsSheet
	}
	opts, comboCharts, err := f.getChartOptions(chart, combo)
	if err != nil {
		return err
	}
	cs := xlsxChartsheet{
		SheetViews: &xlsxChartsheetViews{
			SheetView: []*xlsxChartsheetView{{ZoomScaleAttr: 100, ZoomToFitAttr: true}},
		},
	}
	f.SheetCount++
	wb, _ := f.workbookReader()
	sheetID := 0
	for _, v := range wb.Sheets.Sheet {
		if v.SheetID > sheetID {
			sheetID = v.SheetID
		}
	}
	sheetID++
	path := "xl/chartsheets/sheet" + strconv.Itoa(sheetID) + ".xml"
	f.sheetMap[sheet] = path
	f.Sheet.Store(path, nil)
	drawingID := f.countDrawings() + 1
	chartID := f.countCharts() + 1
	drawingXML := "xl/drawings/drawing" + strconv.Itoa(drawingID) + ".xml"
	f.prepareChartSheetDrawing(&cs, drawingID, sheet)
	drawingRels := "xl/drawings/_rels/drawing" + strconv.Itoa(drawingID) + ".xml.rels"
	drawingRID := f.addRels(drawingRels, SourceRelationshipChart, "../charts/chart"+strconv.Itoa(chartID)+".xml", "")
	if err = f.addSheetDrawingChart(drawingXML, drawingRID, &opts.Format); err != nil {
		return err
	}
	f.addChart(opts, comboCharts)
	if err = f.addContentTypePart(chartID, "chart"); err != nil {
		return err
	}
	_ = f.addContentTypePart(sheetID, "chartsheet")
	_ = f.addContentTypePart(drawingID, "drawings")
	// Update workbook.xml.rels
	rID := f.addRels(f.getWorkbookRelsPath(), SourceRelationshipChartsheet, fmt.Sprintf("/xl/chartsheets/sheet%d.xml", sheetID), "")
	// Update workbook.xml
	f.setWorkbook(sheet, sheetID, rID)
	chartsheet, _ := xml.Marshal(cs)
	f.addSheetNameSpace(sheet, NameSpaceSpreadSheet)
	f.saveFileList(path, replaceRelationshipsBytes(f.replaceNameSpaceBytes(path, chartsheet)))
	return err
}

// getChartOptions provides a function to check format set of the chart and
// create chart format.
func (f *File) getChartOptions(opts *Chart, combo []*Chart) (*Chart, []*Chart, error) {
	var comboCharts []*Chart
	options, err := parseChartOptions(opts)
	if err != nil {
		return options, comboCharts, err
	}
	for _, comboFormat := range combo {
		comboChart, err := parseChartOptions(comboFormat)
		if err != nil {
			return options, comboCharts, err
		}
		if _, ok := chartValAxNumFmtFormatCode[comboChart.Type]; !ok {
			return options, comboCharts, newUnsupportedChartType(comboChart.Type)
		}
		comboCharts = append(comboCharts, comboChart)
	}
	if _, ok := chartValAxNumFmtFormatCode[options.Type]; !ok {
		return options, comboCharts, newUnsupportedChartType(options.Type)
	}
	return options, comboCharts, err
}

// DeleteChart provides a function to delete chart in spreadsheet by given
// worksheet name and cell reference.
func (f *File) DeleteChart(sheet, cell string) error {
	col, row, err := CellNameToCoordinates(cell)
	if err != nil {
		return err
	}
	col--
	row--
	ws, err := f.workSheetReader(sheet)
	if err != nil {
		return err
	}
	if ws.Drawing == nil {
		return err
	}
	drawingXML := strings.ReplaceAll(f.getSheetRelationshipsTargetByID(sheet, ws.Drawing.RID), "..", "xl")
	_, err = f.deleteDrawing(col, row, drawingXML, "Chart")
	return err
}

// GetCharts provides a function to get all charts in a worksheet by given
// worksheet name and cell reference. If the cell has no charts, it will return
// an empty slice.
func (f *File) GetCharts(sheet, cell string) ([]*Chart, error) {
	var col, row int
	filterByCell := cell != ""
	if filterByCell {
		var err error
		col, row, err = CellNameToCoordinates(cell)
		if err != nil {
			return nil, err
		}
		col--
		row--
	}
	ws, err := f.workSheetReader(sheet)
	if err != nil {
		return nil, err
	}
	if ws.Drawing == nil {
		return nil, nil
	}
	target := f.getSheetRelationshipsTargetByID(sheet, ws.Drawing.RID)
	drawingXML := strings.TrimPrefix(strings.ReplaceAll(target, "..", "xl"), "/")
	drawingRelationships := strings.ReplaceAll(
		strings.ReplaceAll(drawingXML, "xl/drawings", "xl/drawings/_rels"), ".xml", ".xml.rels")

	wsDr, _, err := f.drawingParser(drawingXML)
	if err != nil {
		return nil, err
	}

	var charts []*Chart
	matchAnchor := func(anchors []*xdrCellAnchor) error {
		for _, anchor := range anchors {
			if anchor.Pic != nil {
				continue
			}
			// Parse the graphic frame innerxml to get From/To and chart reference.
			// We must supply namespace declarations that were on the parent element.
			wrappedXML := `<decodeCellAnchor xmlns:xdr="` + NameSpaceDrawingMLSpreadSheet.Value +
				`" xmlns:a="` + NameSpaceDrawingML.Value + `">` + anchor.GraphicFrame + `</decodeCellAnchor>`
			deCellAnchor := new(decodeCellAnchor)
			if err = f.xmlNewDecoder(strings.NewReader(wrappedXML)).
				Decode(deCellAnchor); err != nil {
				return err
			}
			from := anchor.From
			if from == nil && deCellAnchor.From != nil {
				from = &xlsxFrom{Col: deCellAnchor.From.Col, ColOff: deCellAnchor.From.ColOff, Row: deCellAnchor.From.Row, RowOff: deCellAnchor.From.RowOff}
			}
			if filterByCell && (from == nil || from.Col != col || from.Row != row) {
				continue
			}
			if deCellAnchor.GraphicFrame == nil || deCellAnchor.GraphicFrame.Graphic == nil ||
				deCellAnchor.GraphicFrame.Graphic.GraphicData.Chart == nil {
				continue
			}
			rID := deCellAnchor.GraphicFrame.Graphic.GraphicData.Chart.RID
			rel := f.getDrawingRelationships(drawingRelationships, rID)
			if rel == nil {
				continue
			}
			chartPath := strings.ReplaceAll(rel.Target, "..", "xl")
			parsed, err := f.parseChartXML(chartPath)
			if err != nil {
				return err
			}
			// Build chart position from anchor From/To
			var pos *ChartPosition
			if from != nil {
				pos = &ChartPosition{
					FromCol:    from.Col,
					FromColOff: from.ColOff,
					FromRow:    from.Row,
					FromRowOff: from.RowOff,
				}
			}
			to := anchor.To
			if to == nil && deCellAnchor.To != nil {
				to = &xlsxTo{Col: deCellAnchor.To.Col, ColOff: deCellAnchor.To.ColOff, Row: deCellAnchor.To.Row, RowOff: deCellAnchor.To.RowOff}
			}
			if pos != nil && to != nil {
				pos.ToCol = to.Col
				pos.ToColOff = to.ColOff
				pos.ToRow = to.Row
				pos.ToRowOff = to.RowOff
			}
			for _, c := range parsed {
				c.Position = pos
			}
			charts = append(charts, parsed...)
		}
		return nil
	}
	if err = matchAnchor(wsDr.OneCellAnchor); err != nil {
		return nil, err
	}
	if err = matchAnchor(wsDr.TwoCellAnchor); err != nil {
		return nil, err
	}
	return charts, nil
}

// parseChartXML parses a chart XML file and returns the chart configuration.
func (f *File) parseChartXML(chartPath string) ([]*Chart, error) {
	content, ok := f.Pkg.Load(chartPath)
	if !ok {
		return nil, nil
	}
	xmlData := content.([]byte)
	var cs xlsxChartSpace
	if err := xml.Unmarshal(xmlData, &cs); err != nil {
		return nil, err
	}
	pa := cs.Chart.PlotArea
	if pa == nil {
		return nil, nil
	}
	nsCS := parseNsChartSpace(xmlData)
	titleRuns := extractTitleRunsFromNsTitle(nsCS.Chart.Title)
	var charts []*Chart
	type chartEntry struct {
		charts []*cCharts
		xmlTag string
	}
	entries := []chartEntry{
		{pa.AreaChart, "areaChart"},
		{pa.Area3DChart, "area3DChart"},
		{pa.BarChart, "barChart"},
		{pa.Bar3DChart, "bar3DChart"},
		{pa.BubbleChart, "bubbleChart"},
		{pa.DoughnutChart, "doughnutChart"},
		{pa.LineChart, "lineChart"},
		{pa.Line3DChart, "line3DChart"},
		{pa.StockChart, "stockChart"},
		{pa.PieChart, "pieChart"},
		{pa.Pie3DChart, "pie3DChart"},
		{pa.OfPieChart, "ofPieChart"},
		{pa.RadarChart, "radarChart"},
		{pa.ScatterChart, "scatterChart"},
		{pa.Surface3DChart, "surface3DChart"},
		{pa.SurfaceChart, "surfaceChart"},
	}
	for _, entry := range entries {
		for _, c := range entry.charts {
			chartType := f.detectChartType(entry.xmlTag, c)
			chart := &Chart{
				Type:   chartType,
				Series: f.extractSeries(c),
				Legend: ChartLegend{
					Position:      parseChartLegendPosition(cs.Chart.Legend),
					ShowLegendKey: extractShowLegendKey(c),
					Overlay:       extractLegendOverlay(cs.Chart.Legend),
					Layout:        parseChartLayout(getLegendLayout(cs.Chart.Legend)),
				},
				Title:       titleRuns,
				TitleLayout: parseChartLayout(getTitleLayout(cs.Chart.Title)),
				PlotArea: ChartPlotArea{
					Layout: parseChartLayout(pa.Layout),
				},
			}
			// Extract AutoTitleDeleted
			if cs.Chart.AutoTitleDeleted != nil {
				chart.AutoTitleDeleted = boolPtr(cs.Chart.AutoTitleDeleted.Val)
			}
			// Extract title overlay
			if cs.Chart.Title != nil && cs.Chart.Title.Overlay != nil && cs.Chart.Title.Overlay.Val != nil {
				chart.TitleOverlay = cs.Chart.Title.Overlay.Val
			}
			// Extract title fill and border from namespace-aware structs
			if nsCS != nil && nsCS.Chart.Title != nil && nsCS.Chart.Title.SpPr != nil {
				chart.TitleFill = extractNsFill(nsCS.Chart.Title.SpPr)
				if nsCS.Chart.Title.SpPr.Ln != nil {
					chart.TitleBorder = extractNsLine(nsCS.Chart.Title.SpPr.Ln)
				}
			}
			// Extract View3D
			if cs.Chart.View3D != nil {
				v3d := &ChartView3D{}
				if cs.Chart.View3D.RotX != nil && cs.Chart.View3D.RotX.Val != nil {
					v3d.RotX = cs.Chart.View3D.RotX.Val
				}
				if cs.Chart.View3D.RotY != nil && cs.Chart.View3D.RotY.Val != nil {
					v3d.RotY = cs.Chart.View3D.RotY.Val
				}
				if cs.Chart.View3D.DepthPercent != nil && cs.Chart.View3D.DepthPercent.Val != nil {
					v3d.DepthPercent = cs.Chart.View3D.DepthPercent.Val
				}
				if cs.Chart.View3D.Perspective != nil && cs.Chart.View3D.Perspective.Val != nil {
					v3d.Perspective = cs.Chart.View3D.Perspective.Val
				}
				if cs.Chart.View3D.RAngAx != nil && cs.Chart.View3D.RAngAx.Val != nil {
					v3d.RAngAx = cs.Chart.View3D.RAngAx.Val
				}
				chart.View3D = v3d
			}
			// Extract PlotVisOnly
			if cs.Chart.PlotVisOnly != nil && cs.Chart.PlotVisOnly.Val != nil {
				chart.PlotVisOnly = cs.Chart.PlotVisOnly.Val
			}
			// Extract ShowDLblsOverMax
			if cs.Chart.ShowDLblsOverMax != nil && cs.Chart.ShowDLblsOverMax.Val != nil {
				chart.ShowDLblsOverMax = cs.Chart.ShowDLblsOverMax.Val
			}
			if c.VaryColors != nil && c.VaryColors.Val != nil {
				chart.VaryColors = c.VaryColors.Val
			}
			if c.HoleSize != nil && c.HoleSize.Val != nil {
				chart.HoleSize = *c.HoleSize.Val
			}
			if c.GapWidth != nil && c.GapWidth.Val != nil {
				chart.GapWidth = uintPtr(uint(*c.GapWidth.Val))
			}
			if c.Overlap != nil && c.Overlap.Val != nil {
				chart.Overlap = c.Overlap.Val
			}
			if c.BubbleScale != nil && c.BubbleScale.Val != nil {
				chart.BubbleSize = int(*c.BubbleScale.Val)
			}
			if c.SplitPos != nil && c.SplitPos.Val != nil {
				chart.PlotArea.SecondPlotValues = *c.SplitPos.Val
			}
			f.extractPlotAreaOpts(c, &chart.PlotArea)
			f.extractPlotAreaNumFmt(c, &chart.PlotArea)
			f.extractShowDataTable(pa, &chart.PlotArea)
			if cs.Chart.DispBlanksAs != nil && cs.Chart.DispBlanksAs.Val != nil {
				chart.ShowBlanksAs = *cs.Chart.DispBlanksAs.Val
			}
			f.extractAxes(pa, chart)
			// Apply namespace-aware SpPr data, axis titles, axis fonts, and legend font
			if nsCS != nil {
				nsCharts := getNsCharts(nsCS.Chart.PlotArea, entry.xmlTag)
				if len(nsCharts) > 0 {
					applyNsChartData(&nsCharts[0], chart)
				}
				if nsCS.Chart.PlotArea != nil && nsCS.Chart.PlotArea.SpPr != nil {
					chart.PlotArea.Fill = extractNsFill(nsCS.Chart.PlotArea.SpPr)
				}
				if nsCS.SpPr != nil {
					chart.Fill = extractNsFill(nsCS.SpPr)
					if nsCS.SpPr.Ln != nil {
						chart.Border = extractNsLine(nsCS.SpPr.Ln)
					}
				}
				extractNsAxesTitles(nsCS.Chart.PlotArea, chart)
				extractNsAxesFonts(nsCS.Chart.PlotArea, chart)
				// Extract legend font, fill, border
				if nsCS.Chart.Legend != nil {
					chart.Legend.Font = extractNsTxPrFont(nsCS.Chart.Legend.TxPr)
					if nsCS.Chart.Legend.SpPr != nil {
						chart.Legend.Fill = extractNsFill(nsCS.Chart.Legend.SpPr)
						if nsCS.Chart.Legend.SpPr.Ln != nil {
							chart.Legend.Border = extractNsLine(nsCS.Chart.Legend.SpPr.Ln)
						}
					}
				}
			}
			charts = append(charts, chart)
		}
	}
	return charts, nil
}

// detectChartType detects the ChartType from cPlotArea chart element fields.
func (f *File) detectChartType(xmlTag string, c *cCharts) ChartType {
	barDir := ""
	if c.BarDir != nil && c.BarDir.Val != nil {
		barDir = *c.BarDir.Val
	}
	grouping := ""
	if c.Grouping != nil && c.Grouping.Val != nil {
		grouping = *c.Grouping.Val
	}
	shape := ""
	if c.Shape != nil && c.Shape.Val != nil {
		shape = *c.Shape.Val
	}
	wireframe := false
	if c.Wireframe != nil && c.Wireframe.Val != nil {
		wireframe = *c.Wireframe.Val
	}
	ofPieType := ""
	if c.OfPieType != nil && c.OfPieType.Val != nil {
		ofPieType = *c.OfPieType.Val
	}
	hasUpDownBars := c.UpDownBars != nil

	switch xmlTag {
	case "areaChart":
		switch grouping {
		case "stacked":
			return AreaStacked
		case "percentStacked":
			return AreaPercentStacked
		default:
			return Area
		}
	case "area3DChart":
		switch grouping {
		case "stacked":
			return Area3DStacked
		case "percentStacked":
			return Area3DPercentStacked
		default:
			return Area3D
		}
	case "barChart":
		if barDir == "bar" {
			switch grouping {
			case "stacked":
				return BarStacked
			case "percentStacked":
				return BarPercentStacked
			default:
				return Bar
			}
		}
		switch grouping {
		case "stacked":
			return ColStacked
		case "percentStacked":
			return ColPercentStacked
		default:
			return Col
		}
	case "bar3DChart":
		isBar := barDir == "bar"
		switch shape {
		case "cone":
			if isBar {
				switch grouping {
				case "stacked":
					return Bar3DConeStacked
				case "percentStacked":
					return Bar3DConePercentStacked
				default:
					return Bar3DConeClustered
				}
			}
			switch grouping {
			case "stacked":
				return Col3DConeStacked
			case "percentStacked":
				return Col3DConePercentStacked
			case "clustered":
				return Col3DConeClustered
			default:
				return Col3DCone
			}
		case "pyramid":
			if isBar {
				switch grouping {
				case "stacked":
					return Bar3DPyramidStacked
				case "percentStacked":
					return Bar3DPyramidPercentStacked
				default:
					return Bar3DPyramidClustered
				}
			}
			switch grouping {
			case "stacked":
				return Col3DPyramidStacked
			case "percentStacked":
				return Col3DPyramidPercentStacked
			case "clustered":
				return Col3DPyramidClustered
			default:
				return Col3DPyramid
			}
		case "cylinder":
			if isBar {
				switch grouping {
				case "stacked":
					return Bar3DCylinderStacked
				case "percentStacked":
					return Bar3DCylinderPercentStacked
				default:
					return Bar3DCylinderClustered
				}
			}
			switch grouping {
			case "stacked":
				return Col3DCylinderStacked
			case "percentStacked":
				return Col3DCylinderPercentStacked
			case "clustered":
				return Col3DCylinderClustered
			default:
				return Col3DCylinder
			}
		default:
			if isBar {
				switch grouping {
				case "stacked":
					return Bar3DStacked
				case "percentStacked":
					return Bar3DPercentStacked
				default:
					return Bar3DClustered
				}
			}
			switch grouping {
			case "stacked":
				return Col3DStacked
			case "percentStacked":
				return Col3DPercentStacked
			case "clustered":
				return Col3DClustered
			default:
				return Col3D
			}
		}
	case "lineChart":
		return Line
	case "line3DChart":
		return Line3D
	case "pieChart":
		return Pie
	case "pie3DChart":
		return Pie3D
	case "ofPieChart":
		if ofPieType == "bar" {
			return BarOfPie
		}
		return PieOfPie
	case "doughnutChart":
		return Doughnut
	case "radarChart":
		return Radar
	case "scatterChart":
		return Scatter
	case "bubbleChart":
		bubble3D := false
		if c.Ser != nil {
			for _, s := range *c.Ser {
				if s.Bubble3D != nil && s.Bubble3D.Val != nil && *s.Bubble3D.Val {
					bubble3D = true
					break
				}
			}
		}
		if bubble3D {
			return Bubble3D
		}
		return Bubble
	case "surface3DChart":
		if wireframe {
			return WireframeSurface3D
		}
		return Surface3D
	case "surfaceChart":
		if wireframe {
			return WireframeContour
		}
		return Contour
	case "stockChart":
		if hasUpDownBars {
			return StockOpenHighLowClose
		}
		return StockHighLowClose
	}
	return Col
}

// extractSeries extracts chart series from cCharts.
func (f *File) extractSeries(c *cCharts) []ChartSeries {
	if c.Ser == nil {
		return nil
	}
	var series []ChartSeries
	for _, s := range *c.Ser {
		cs := ChartSeries{}
		if s.Tx != nil && s.Tx.StrRef != nil {
			cs.Name = s.Tx.StrRef.F
		}
		if s.Cat != nil && s.Cat.StrRef != nil {
			cs.Categories = s.Cat.StrRef.F
		}
		if s.Val != nil && s.Val.NumRef != nil {
			cs.Values = s.Val.NumRef.F
		}
		if s.XVal != nil && s.XVal.StrRef != nil {
			cs.Categories = s.XVal.StrRef.F
		}
		if s.YVal != nil && s.YVal.NumRef != nil {
			cs.Values = s.YVal.NumRef.F
		}
		if s.BubbleSize != nil && s.BubbleSize.NumRef != nil {
			cs.Sizes = s.BubbleSize.NumRef.F
		}
		if s.Smooth != nil && s.Smooth.Val != nil {
			cs.Line.Smooth = *s.Smooth.Val
		}
		series = append(series, cs)
	}
	return series
}

// extractPlotAreaOpts extracts plot area options from chart data.
func (f *File) extractPlotAreaOpts(c *cCharts, pa *ChartPlotArea) {
	if c.DLbls == nil {
		return
	}
	if c.DLbls.ShowVal != nil && c.DLbls.ShowVal.Val != nil {
		pa.ShowVal = *c.DLbls.ShowVal.Val
	}
	if c.DLbls.ShowCatName != nil && c.DLbls.ShowCatName.Val != nil {
		pa.ShowCatName = *c.DLbls.ShowCatName.Val
	}
	if c.DLbls.ShowSerName != nil && c.DLbls.ShowSerName.Val != nil {
		pa.ShowSerName = *c.DLbls.ShowSerName.Val
	}
	if c.DLbls.ShowPercent != nil && c.DLbls.ShowPercent.Val != nil {
		pa.ShowPercent = *c.DLbls.ShowPercent.Val
	}
	if c.DLbls.ShowBubbleSize != nil && c.DLbls.ShowBubbleSize.Val != nil {
		pa.ShowBubbleSize = *c.DLbls.ShowBubbleSize.Val
	}
	if c.DLbls.ShowLeaderLines != nil && c.DLbls.ShowLeaderLines.Val != nil {
		pa.ShowLeaderLines = *c.DLbls.ShowLeaderLines.Val
	}
}

// applyNsChartData applies namespace-aware SpPr data to chart series and
// up/down bars from the decoded namespace chart structs.
func applyNsChartData(nsCharts *decodeNsCharts, chart *Chart) {
	// Apply series fill/line/marker from namespace-aware structs
	for i := range nsCharts.Ser {
		if i >= len(chart.Series) {
			break
		}
		nsSer := &nsCharts.Ser[i]
		if nsSer.SpPr != nil {
			chart.Series[i].Fill = extractNsFill(nsSer.SpPr)
			if nsSer.SpPr.Ln != nil {
				chart.Series[i].Line = extractNsLine(nsSer.SpPr.Ln)
			}
		}
		if nsSer.Marker != nil {
			if nsSer.Marker.Symbol != nil && nsSer.Marker.Symbol.Val != nil {
				chart.Series[i].Marker.Symbol = *nsSer.Marker.Symbol.Val
			}
			if nsSer.Marker.Size != nil && nsSer.Marker.Size.Val != nil {
				chart.Series[i].Marker.Size = *nsSer.Marker.Size.Val
			}
			if nsSer.Marker.SpPr != nil {
				chart.Series[i].Marker.Fill = extractNsFill(nsSer.Marker.SpPr)
				if nsSer.Marker.SpPr.Ln != nil {
					chart.Series[i].Marker.Border = extractNsLine(nsSer.Marker.SpPr.Ln)
				}
			}
		}
		if nsSer.DLbls != nil {
			if nsSer.DLbls.DLblPos != nil && nsSer.DLbls.DLblPos.Val != nil {
				chart.Series[i].DataLabelPosition = reverseDataLabelPosition(*nsSer.DLbls.DLblPos.Val)
			}
			if nsSer.DLbls.SpPr != nil {
				chart.Series[i].DataLabel.Fill = extractNsFill(nsSer.DLbls.SpPr)
			}
			if f := extractNsTxPrFont(nsSer.DLbls.TxPr); f != nil {
				chart.Series[i].DataLabel.Font = *f
			}
		}
	}
	// Apply up/down bars
	if nsCharts.UpDownBars != nil {
		if nsCharts.UpDownBars.UpBars != nil && nsCharts.UpDownBars.UpBars.SpPr != nil {
			chart.PlotArea.UpBars.Fill = extractNsFill(nsCharts.UpDownBars.UpBars.SpPr)
			if nsCharts.UpDownBars.UpBars.SpPr.Ln != nil {
				chart.PlotArea.UpBars.Border = extractNsLine(nsCharts.UpDownBars.UpBars.SpPr.Ln)
			}
		}
		if nsCharts.UpDownBars.DownBars != nil && nsCharts.UpDownBars.DownBars.SpPr != nil {
			chart.PlotArea.DownBars.Fill = extractNsFill(nsCharts.UpDownBars.DownBars.SpPr)
			if nsCharts.UpDownBars.DownBars.SpPr.Ln != nil {
				chart.PlotArea.DownBars.Border = extractNsLine(nsCharts.UpDownBars.DownBars.SpPr.Ln)
			}
		}
	}
}

// reverseDashType converts XML dash type string back to ChartDashType.
func reverseDashType(s string) ChartDashType {
	revDash := map[string]ChartDashType{
		"solid":         ChartDashSolid,
		"dot":           ChartDashDot,
		"dash":          ChartDashDash,
		"lgDash":        ChartDashLgDash,
		"dashDot":       ChartDashSashDot,
		"lgDashDot":     ChartDashLgDashDot,
		"lgDashDotDot":  ChartDashLgDashDotDot,
		"sysDash":       ChartDashSysDash,
		"sysDot":        ChartDashSysDot,
		"sysDashDot":    ChartDashSysDashDot,
		"sysDashDotDot": ChartDashSysDashDotDot,
	}
	if d, ok := revDash[s]; ok {
		return d
	}
	return ChartDashUnset
}


// reverseDataLabelPosition converts XML data label position to enum.
func reverseDataLabelPosition(s string) ChartDataLabelPositionType {
	revPos := map[string]ChartDataLabelPositionType{
		"t":      ChartDataLabelsPositionAbove,
		"b":      ChartDataLabelsPositionBelow,
		"l":      ChartDataLabelsPositionLeft,
		"r":      ChartDataLabelsPositionRight,
		"ctr":    ChartDataLabelsPositionCenter,
		"inBase": ChartDataLabelsPositionInsideBase,
		"inEnd":  ChartDataLabelsPositionInsideEnd,
		"outEnd": ChartDataLabelsPositionOutsideEnd,
		"bestFit": ChartDataLabelsPositionBestFit,
	}
	if p, ok := revPos[s]; ok {
		return p
	}
	return ChartDataLabelsPositionUnset
}


// extractPlotAreaNumFmt extracts plot area number format from chart DLbls.
func (f *File) extractPlotAreaNumFmt(c *cCharts, plotArea *ChartPlotArea) {
	if c.DLbls != nil && c.DLbls.NumFmt != nil {
		plotArea.NumFmt = ChartNumFmt{
			CustomNumFmt: c.DLbls.NumFmt.FormatCode,
			SourceLinked: c.DLbls.NumFmt.SourceLinked,
		}
	}
}

// extractShowDataTable extracts data table visibility from plot area.
func (f *File) extractShowDataTable(pa *cPlotArea, plotArea *ChartPlotArea) {
	if pa.DTable != nil {
		plotArea.ShowDataTable = true
		if pa.DTable.ShowKeys != nil && pa.DTable.ShowKeys.Val != nil {
			plotArea.ShowDataTableKeys = *pa.DTable.ShowKeys.Val
		}
	}
}

// extractShowLegendKey extracts ShowLegendKey from chart DLbls.
func extractShowLegendKey(c *cCharts) bool {
	if c.DLbls != nil && c.DLbls.ShowLegendKey != nil && c.DLbls.ShowLegendKey.Val != nil {
		return *c.DLbls.ShowLegendKey.Val
	}
	return false
}


// extractAxes extracts X and Y axis properties from the plot area.
func (f *File) extractAxes(pa *cPlotArea, chart *Chart) {
	// Category axis → XAxis
	if len(pa.CatAx) > 0 {
		f.extractAxisOpts(pa.CatAx[0], &chart.XAxis)
	}
	if len(pa.DateAx) > 0 {
		f.extractAxisOpts(pa.DateAx[0], &chart.XAxis)
	}
	// Value axis → YAxis
	if len(pa.ValAx) > 0 {
		f.extractAxisOpts(pa.ValAx[0], &chart.YAxis)
		// If there's a secondary value axis
		if len(pa.ValAx) > 1 {
			chart.YAxis.Secondary = true
		}
	}
}

// extractNsAxesTitles extracts axis titles using namespace-aware structs.
func extractNsAxesTitles(nsPa *decodeNsPlotArea, chart *Chart) {
	if nsPa == nil {
		return
	}
	// CatAx / DateAx → XAxis.Title
	if len(nsPa.CatAx) > 0 && nsPa.CatAx[0].Title != nil {
		chart.XAxis.Title = extractNsRichTitle(nsPa.CatAx[0].Title)
	}
	if len(nsPa.DateAx) > 0 && nsPa.DateAx[0].Title != nil {
		chart.XAxis.Title = extractNsRichTitle(nsPa.DateAx[0].Title)
	}
	// ValAx → YAxis.Title
	if len(nsPa.ValAx) > 0 && nsPa.ValAx[0].Title != nil {
		chart.YAxis.Title = extractNsRichTitle(nsPa.ValAx[0].Title)
	}
}

// extractNsAxesFonts extracts axis label fonts and alignment using namespace-aware TxPr.
func extractNsAxesFonts(nsPa *decodeNsPlotArea, chart *Chart) {
	if nsPa == nil {
		return
	}
	applyTxPr := func(txPr *decodeNsTxPr, axis *ChartAxis) {
		if txPr == nil {
			return
		}
		if f := extractNsTxPrFont(txPr); f != nil {
			axis.Font = *f
		}
		if txPr.BodyPr != nil {
			if txPr.BodyPr.Rot != 0 {
				axis.Alignment.TextRotation = txPr.BodyPr.Rot / 60000
			}
			if txPr.BodyPr.Vert != "" && txPr.BodyPr.Vert != "horz" {
				axis.Alignment.Vertical = txPr.BodyPr.Vert
			}
		}
	}
	// CatAx / DateAx → XAxis
	if len(nsPa.CatAx) > 0 {
		applyTxPr(nsPa.CatAx[0].TxPr, &chart.XAxis)
	}
	if len(nsPa.DateAx) > 0 {
		applyTxPr(nsPa.DateAx[0].TxPr, &chart.XAxis)
	}
	// ValAx → YAxis
	if len(nsPa.ValAx) > 0 {
		applyTxPr(nsPa.ValAx[0].TxPr, &chart.YAxis)
	}
}

// extractNsRichTitle extracts []RichTextRun from a decodeRichTitle.
func extractNsRichTitle(dt *decodeRichTitle) []RichTextRun {
	if dt == nil || dt.Tx.Rich == nil {
		return nil
	}
	var runs []RichTextRun
	for _, p := range dt.Tx.Rich.P {
		if p.R == nil {
			continue
		}
		run := RichTextRun{Text: p.R.T}
		if p.R.RPr != nil {
			run.Font = extractNsRPrFont(p.R.RPr)
		}
		runs = append(runs, run)
	}
	return runs
}

// extractAxisOpts extracts axis properties from cAxs.
func (f *File) extractAxisOpts(ax *cAxs, axis *ChartAxis) {
	if ax == nil {
		return
	}
	if ax.Delete != nil && ax.Delete.Val != nil {
		axis.None = *ax.Delete.Val
	}
	if ax.MajorGridlines != nil {
		axis.MajorGridLines = true
	}
	if ax.MinorGridlines != nil {
		axis.MinorGridLines = true
	}
	if ax.MajorUnit != nil && ax.MajorUnit.Val != nil {
		axis.MajorUnit = *ax.MajorUnit.Val
	}
	if ax.MinorUnit != nil && ax.MinorUnit.Val != nil {
		axis.MinorUnit = *ax.MinorUnit.Val
	}
	if ax.MajorTickMark != nil && ax.MajorTickMark.Val != nil {
		axis.MajorTickMark = reverseTickMarkType(*ax.MajorTickMark.Val)
	}
	if ax.MinorTickMark != nil && ax.MinorTickMark.Val != nil {
		axis.MinorTickMark = reverseTickMarkType(*ax.MinorTickMark.Val)
	}
	if ax.TickLblPos != nil && ax.TickLblPos.Val != nil {
		axis.TickLabelPosition = reverseTickLabelPosition(*ax.TickLblPos.Val)
	}
	if ax.TickLblSkip != nil && ax.TickLblSkip.Val != nil {
		axis.TickLabelSkip = *ax.TickLblSkip.Val
	}
	if ax.Scaling != nil {
		if ax.Scaling.Orientation != nil && ax.Scaling.Orientation.Val != nil && *ax.Scaling.Orientation.Val == "maxMin" {
			axis.ReverseOrder = true
		}
		if ax.Scaling.Max != nil && ax.Scaling.Max.Val != nil {
			axis.Maximum = ax.Scaling.Max.Val
		}
		if ax.Scaling.Min != nil && ax.Scaling.Min.Val != nil {
			axis.Minimum = ax.Scaling.Min.Val
		}
		if ax.Scaling.LogBase != nil && ax.Scaling.LogBase.Val != nil {
			axis.LogBase = *ax.Scaling.LogBase.Val
		}
	}
	if ax.NumFmt != nil {
		axis.NumFmt = ChartNumFmt{
			CustomNumFmt: ax.NumFmt.FormatCode,
			SourceLinked: ax.NumFmt.SourceLinked,
		}
	}
}

// reverseTickLabelPosition converts XML tick label position to enum.
func reverseTickLabelPosition(s string) ChartTickLabelPositionType {
	revPos := map[string]ChartTickLabelPositionType{
		"nextTo": ChartTickLabelNextToAxis,
		"high":   ChartTickLabelHigh,
		"low":    ChartTickLabelLow,
		"none":   ChartTickLabelNone,
	}
	if p, ok := revPos[s]; ok {
		return p
	}
	return ChartTickLabelNextToAxis
}

// reverseTickMarkType converts XML tick mark type string to ChartTickMarkType.
func reverseTickMarkType(s string) ChartTickMarkType {
	revTick := map[string]ChartTickMarkType{
		"none":    ChartTickMarkNone,
		"in":      ChartTickMarkInside,
		"out":     ChartTickMarkOutside,
		"cross":   ChartTickMarkCross,
	}
	if t, ok := revTick[s]; ok {
		return t
	}
	return ChartTickMarkNone
}

// parseChartLegendPosition returns the legend position string from cLegend.
func parseChartLegendPosition(legend *cLegend) string {
	if legend == nil {
		return "none"
	}
	if legend.LegendPos == nil || legend.LegendPos.Val == nil {
		return "right"
	}
	revLegendPos := map[string]string{
		"b":  "bottom",
		"l":  "left",
		"r":  "right",
		"t":  "top",
		"tr": "top_right",
	}
	if pos, ok := revLegendPos[*legend.LegendPos.Val]; ok {
		return pos
	}
	return "right"
}

// getLegendLayout returns the layout from a cLegend, or nil.
func getLegendLayout(legend *cLegend) *cLayout {
	if legend == nil {
		return nil
	}
	return legend.Layout
}

// extractLegendOverlay returns the overlay value from a cLegend.
func extractLegendOverlay(legend *cLegend) *bool {
	if legend == nil || legend.Overlay == nil || legend.Overlay.Val == nil {
		return nil
	}
	return legend.Overlay.Val
}

// getTitleLayout returns the layout from a cTitle, or nil.
func getTitleLayout(title *cTitle) *cLayout {
	if title == nil {
		return nil
	}
	return title.Layout
}

// parseChartLayout converts a cLayout XML structure to a ChartLayout.
func parseChartLayout(layout *cLayout) *ChartLayout {
	if layout == nil || layout.ManualLayout == nil {
		return nil
	}
	ml := layout.ManualLayout
	cl := &ChartLayout{}
	if ml.X != nil && ml.X.Val != nil {
		cl.X = *ml.X.Val
	}
	if ml.Y != nil && ml.Y.Val != nil {
		cl.Y = *ml.Y.Val
	}
	if ml.W != nil && ml.W.Val != nil {
		cl.Width = *ml.W.Val
	}
	if ml.H != nil && ml.H.Val != nil {
		cl.Height = *ml.H.Val
	}
	return cl
}

// The following decode* types are used for deserializing chart XML with proper
// namespace handling. The internal cSpPr/aSolidFill/aLn etc. use "a:" prefix
// tags which only work for marshaling, not unmarshaling. These decode structs
// use full namespace URIs.

const nsChart = "http://schemas.openxmlformats.org/drawingml/2006/chart"
const nsDrawingML = "http://schemas.openxmlformats.org/drawingml/2006/main"

type decodeChartFull struct {
	XMLName xml.Name `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart chartSpace"`
	Chart   struct {
		Title *decodeRichTitle `xml:"title"`
	} `xml:"chart"`
	SpPr *decodeNsSpPr `xml:"spPr"`
}

type decodeRichTitle struct {
	Tx struct {
		Rich *decodeRich `xml:"rich"`
	} `xml:"tx"`
}

type decodeRich struct {
	P []decodeRichP `xml:"http://schemas.openxmlformats.org/drawingml/2006/main p"`
}

type decodeRichP struct {
	R *decodeRichR `xml:"http://schemas.openxmlformats.org/drawingml/2006/main r"`
}

type decodeRichR struct {
	RPr *decodeNsRPr `xml:"http://schemas.openxmlformats.org/drawingml/2006/main rPr"`
	T   string       `xml:"http://schemas.openxmlformats.org/drawingml/2006/main t"`
}

// decodeNsRPr handles a:rPr (run properties) for font extraction.
type decodeNsRPr struct {
	B         bool            `xml:"b,attr"`
	I         bool            `xml:"i,attr"`
	Strike    string          `xml:"strike,attr,omitempty"`
	U         string          `xml:"u,attr,omitempty"`
	Sz        float64         `xml:"sz,attr,omitempty"`
	SolidFill *decodeNsFill   `xml:"http://schemas.openxmlformats.org/drawingml/2006/main solidFill"`
	Latin     *decodeNsLatin  `xml:"http://schemas.openxmlformats.org/drawingml/2006/main latin"`
}

type decodeNsLatin struct {
	Typeface string `xml:"typeface,attr"`
}

// decodeNsSpPr handles a:solidFill, a:noFill, a:ln with proper namespaces.
type decodeNsSpPr struct {
	NoFill    *string          `xml:"http://schemas.openxmlformats.org/drawingml/2006/main noFill"`
	SolidFill *decodeNsFill    `xml:"http://schemas.openxmlformats.org/drawingml/2006/main solidFill"`
	Ln        *decodeNsLn      `xml:"http://schemas.openxmlformats.org/drawingml/2006/main ln"`
}

type decodeNsFill struct {
	SchemeClr *decodeNsSchemeClr `xml:"http://schemas.openxmlformats.org/drawingml/2006/main schemeClr"`
	SrgbClr   *decodeNsSrgbClr   `xml:"http://schemas.openxmlformats.org/drawingml/2006/main srgbClr"`
}

type decodeNsSchemeClr struct {
	Val string `xml:"val,attr"`
}

type decodeNsSrgbClr struct {
	Val   string          `xml:"val,attr"`
	Alpha *decodeNsAlpha  `xml:"http://schemas.openxmlformats.org/drawingml/2006/main alpha"`
}

type decodeNsAlpha struct {
	Val int `xml:"val,attr"`
}

type decodeNsLn struct {
	W         int              `xml:"w,attr,omitempty"`
	NoFill    *string          `xml:"http://schemas.openxmlformats.org/drawingml/2006/main noFill"`
	SolidFill *decodeNsFill    `xml:"http://schemas.openxmlformats.org/drawingml/2006/main solidFill"`
	PrstDash  *decodeNsDash    `xml:"http://schemas.openxmlformats.org/drawingml/2006/main prstDash"`
}

type decodeNsDash struct {
	Val string `xml:"val,attr"`
}

// decodeNsSer handles series with proper namespace for SpPr.
type decodeNsSer struct {
	IDx    *attrValInt    `xml:"idx"`
	SpPr   *decodeNsSpPr  `xml:"spPr"`
	Marker *decodeNsMarker `xml:"marker"`
	DLbls  *decodeNsDLbls  `xml:"dLbls"`
}

type decodeNsMarker struct {
	Symbol *attrValString `xml:"symbol"`
	Size   *attrValInt    `xml:"size"`
	SpPr   *decodeNsSpPr  `xml:"spPr"`
}

type decodeNsDLbls struct {
	NumFmt  *cNumFmt       `xml:"numFmt"`
	SpPr    *decodeNsSpPr  `xml:"spPr"`
	TxPr    *decodeNsTxPr  `xml:"txPr"`
	DLblPos *attrValString `xml:"dLblPos"`
}

// decodeNsCharts handles chart-level data with proper SpPr namespace.
type decodeNsCharts struct {
	Ser        []decodeNsSer       `xml:"ser"`
	DLbls      *decodeNsDLbls      `xml:"dLbls"`
	UpDownBars *decodeNsUpDownBars `xml:"upDownBars"`
}

type decodeNsUpDownBars struct {
	UpBars   *decodeNsChartLines `xml:"upBars"`
	DownBars *decodeNsChartLines `xml:"downBars"`
}

type decodeNsChartLines struct {
	SpPr *decodeNsSpPr `xml:"spPr"`
}

// decodeNsTxPr handles text properties for font extraction.
type decodeNsTxPr struct {
	BodyPr *decodeNsBodyPr `xml:"http://schemas.openxmlformats.org/drawingml/2006/main bodyPr"`
	P      []decodeNsTxPrP `xml:"http://schemas.openxmlformats.org/drawingml/2006/main p"`
}

type decodeNsBodyPr struct {
	Rot  int    `xml:"rot,attr"`
	Vert string `xml:"vert,attr,omitempty"`
}

type decodeNsTxPrP struct {
	PPr *decodeNsTxPrPPr `xml:"http://schemas.openxmlformats.org/drawingml/2006/main pPr"`
}

type decodeNsTxPrPPr struct {
	DefRPr *decodeNsRPr `xml:"http://schemas.openxmlformats.org/drawingml/2006/main defRPr"`
}

// decodeNsAxs handles axis title and TxPr extraction with proper namespace.
type decodeNsAxs struct {
	Title *decodeRichTitle `xml:"title"`
	TxPr  *decodeNsTxPr   `xml:"txPr"`
}

// decodeNsLegend handles legend with TxPr and SpPr for font/fill/border extraction.
type decodeNsLegend struct {
	TxPr *decodeNsTxPr `xml:"txPr"`
	SpPr *decodeNsSpPr `xml:"spPr"`
}

// decodeNsPlotArea for extracting SpPr from plot area elements.
type decodeNsPlotArea struct {
	AreaChart      []decodeNsCharts `xml:"areaChart"`
	Area3DChart    []decodeNsCharts `xml:"area3DChart"`
	BarChart       []decodeNsCharts `xml:"barChart"`
	Bar3DChart     []decodeNsCharts `xml:"bar3DChart"`
	BubbleChart    []decodeNsCharts `xml:"bubbleChart"`
	DoughnutChart  []decodeNsCharts `xml:"doughnutChart"`
	LineChart      []decodeNsCharts `xml:"lineChart"`
	Line3DChart    []decodeNsCharts `xml:"line3DChart"`
	StockChart     []decodeNsCharts `xml:"stockChart"`
	PieChart       []decodeNsCharts `xml:"pieChart"`
	Pie3DChart     []decodeNsCharts `xml:"pie3DChart"`
	OfPieChart     []decodeNsCharts `xml:"ofPieChart"`
	RadarChart     []decodeNsCharts `xml:"radarChart"`
	ScatterChart   []decodeNsCharts `xml:"scatterChart"`
	Surface3DChart []decodeNsCharts `xml:"surface3DChart"`
	SurfaceChart   []decodeNsCharts `xml:"surfaceChart"`
	CatAx          []decodeNsAxs    `xml:"catAx"`
	ValAx          []decodeNsAxs    `xml:"valAx"`
	DateAx         []decodeNsAxs    `xml:"dateAx"`
	SerAx          []decodeNsAxs    `xml:"serAx"`
	SpPr           *decodeNsSpPr    `xml:"spPr"`
}

// decodeNsTitleFull handles title with SpPr for fill/border extraction.
type decodeNsTitleFull struct {
	Tx   struct {
		Rich *decodeRich `xml:"rich"`
	} `xml:"tx"`
	SpPr *decodeNsSpPr `xml:"spPr"`
}

type decodeNsChartSpace struct {
	XMLName xml.Name `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart chartSpace"`
	Chart   struct {
		Title    *decodeNsTitleFull `xml:"title"`
		PlotArea *decodeNsPlotArea  `xml:"plotArea"`
		Legend   *decodeNsLegend    `xml:"legend"`
	} `xml:"chart"`
	SpPr *decodeNsSpPr `xml:"spPr"`
}

// extractTitleRunsFromNsTitle extracts rich text runs from decodeNsTitleFull.
func extractTitleRunsFromNsTitle(title *decodeNsTitleFull) []RichTextRun {
	if title == nil || title.Tx.Rich == nil {
		return nil
	}
	var runs []RichTextRun
	for _, p := range title.Tx.Rich.P {
		if p.R == nil {
			continue
		}
		run := RichTextRun{Text: p.R.T}
		if p.R.RPr != nil {
			run.Font = extractNsRPrFont(p.R.RPr)
		}
		runs = append(runs, run)
	}
	return runs
}

// extractNsRPrFont converts decodeNsRPr to a Font struct.
func extractNsRPrFont(rpr *decodeNsRPr) *Font {
	if rpr == nil {
		return nil
	}
	f := &Font{
		Bold:   rpr.B,
		Italic: rpr.I,
	}
	if rpr.Sz > 0 {
		f.Size = rpr.Sz / 100
	}
	if rpr.Strike == "sngStrike" || rpr.Strike == "dblStrike" {
		f.Strike = true
	}
	if rpr.U != "" {
		f.Underline = rpr.U
	}
	if rpr.Latin != nil && rpr.Latin.Typeface != "" {
		f.Family = rpr.Latin.Typeface
	}
	if rpr.SolidFill != nil && rpr.SolidFill.SrgbClr != nil {
		f.Color = rpr.SolidFill.SrgbClr.Val
	}
	// Return nil if font has no meaningful properties set
	if !f.Bold && !f.Italic && !f.Strike && f.Size == 0 && f.Family == "" && f.Color == "" && f.Underline == "" {
		return nil
	}
	return f
}

// extractNsTxPrFont extracts a Font from a decodeNsTxPr text properties struct.
func extractNsTxPrFont(txPr *decodeNsTxPr) *Font {
	if txPr == nil {
		return nil
	}
	for _, p := range txPr.P {
		if p.PPr != nil && p.PPr.DefRPr != nil {
			return extractNsRPrFont(p.PPr.DefRPr)
		}
	}
	return nil
}

// parseNsChartSpace parses chart XML with namespace-aware decode structs for
// extracting a:-prefixed properties (SpPr, fills, lines, markers).
func parseNsChartSpace(xmlData []byte) *decodeNsChartSpace {
	var ns decodeNsChartSpace
	if err := xml.Unmarshal(xmlData, &ns); err != nil {
		return nil
	}
	return &ns
}

// getNsCharts returns the decodeNsCharts slice matching the given xmlTag.
func getNsCharts(pa *decodeNsPlotArea, xmlTag string) []decodeNsCharts {
	if pa == nil {
		return nil
	}
	switch xmlTag {
	case "areaChart":
		return pa.AreaChart
	case "area3DChart":
		return pa.Area3DChart
	case "barChart":
		return pa.BarChart
	case "bar3DChart":
		return pa.Bar3DChart
	case "bubbleChart":
		return pa.BubbleChart
	case "doughnutChart":
		return pa.DoughnutChart
	case "lineChart":
		return pa.LineChart
	case "line3DChart":
		return pa.Line3DChart
	case "stockChart":
		return pa.StockChart
	case "pieChart":
		return pa.PieChart
	case "pie3DChart":
		return pa.Pie3DChart
	case "ofPieChart":
		return pa.OfPieChart
	case "radarChart":
		return pa.RadarChart
	case "scatterChart":
		return pa.ScatterChart
	case "surface3DChart":
		return pa.Surface3DChart
	case "surfaceChart":
		return pa.SurfaceChart
	}
	return nil
}

// extractNsFill converts decodeNsSpPr to a Fill.
func extractNsFill(spPr *decodeNsSpPr) Fill {
	if spPr == nil || spPr.SolidFill == nil || spPr.SolidFill.SrgbClr == nil {
		return Fill{}
	}
	f := Fill{Type: "pattern", Pattern: 1, Color: []string{spPr.SolidFill.SrgbClr.Val}}
	if spPr.SolidFill.SrgbClr.Alpha != nil {
		f.Transparency = 100 - spPr.SolidFill.SrgbClr.Alpha.Val/1000
	}
	return f
}

// extractNsLine converts decodeNsLn to a ChartLine.
func extractNsLine(ln *decodeNsLn) ChartLine {
	if ln == nil {
		return ChartLine{}
	}
	cl := ChartLine{}
	if ln.W > 0 {
		cl.Width = float64(ln.W) / 12700
	}
	if ln.NoFill != nil {
		cl.Type = ChartLineNone
	} else if ln.SolidFill != nil {
		cl.Type = ChartLineSolid
		if ln.SolidFill.SrgbClr != nil {
			cl.Fill = Fill{Type: "pattern", Pattern: 1, Color: []string{ln.SolidFill.SrgbClr.Val}}
		}
	}
	if ln.PrstDash != nil {
		cl.Dash = reverseDashType(ln.PrstDash.Val)
	}
	return cl
}

// countCharts provides a function to get chart files count storage in the
// folder xl/charts.
func (f *File) countCharts() int {
	count := 0
	f.Pkg.Range(func(k, v interface{}) bool {
		if strings.Contains(k.(string), "xl/charts/chart") {
			count++
		}
		return true
	})
	return count
}

// ptToEMUs provides a function to convert pt to EMUs, 1 pt = 12700 EMUs. The
// range of pt is 0.25pt - 999pt. If the value of pt is outside the range, the
// default EMUs will be returned.
func (f *File) ptToEMUs(pt float64) int {
	if 0.25 > pt || pt > 999 {
		return 25400
	}
	return int(12700 * pt)
}
